POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Pablo",
    "number": "6546554654"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "sdfsdf",
    "number": ""
}